#! /bin/bash

TIMEOUT_PATH=$(command -v timeout)
TIMEOUT_PATH=${TIMEOUT_PATH:-"vendor/coreutils-8.32/src/timeout"}
FFMPEG_PATH=$(command -v ffmpeg)
FFMPEG_PATH=${FFMPEG_PATH:-"vendor/ffmpeg-4.2.3/ffmpeg"}

if [ $# -lt 1 ]; then
    printf "too few arguments  Usage:$0 [run file] [option]\n"
    exit 2
fi

TARGET=$1
shift
printf "Running virtual LED display (timeout:30s)... "
# "--foreground" によって Ctrl-C でも終了できるようにする
${TIMEOUT_PATH} --foreground 30 ./${TARGET} $@
printf "Done\n"

if [ ! -e log/rectmp/0001.bmp ]; then
    printf "No bmp file in 'log/rectmp' directory\n"
    exit 2
fi

#連番画像から動画生成
printf "Writing to video file... "
${FFMPEG_PATH} -r 30 -s 454x454 -i log/rectmp/%04d.bmp -b:v 6144k log/rectmp/tmp.mp4 -loglevel fatal

if [ $? = 0 ]; then
    printf "Done\n"
else
    printf "Failure\n"
    exit 2
fi

rm log/rectmp/*.bmp
if [ ! -e log/rectmp/tmp.mp4 ]; then
    printf "'log/rectmp/tmp.mp4': No such file\n"
    exit 2
fi
TIME=$(date +%m%d_%H-%M-%S)
mv log/rectmp/tmp.mp4 log/led_matrix_${TARGET}_${TIME}.mp4
printf "save to file 'log/led_matrix_${TARGET}_${TIME}.mp4'\n"
